#' Synthetic example PFT cohort
#'
#' A small synthetic cohort of 20 patients spanning the clinical
#' patterns the package classifies (Normal, Obstructed, Restricted,
#' Mixed, Non-specific, PRISm) plus a few bronchodilator-response
#' cases. Demographics are random within plausible ranges; measured
#' values were hand-picked so that each row lands in its target
#' pattern after the GLI reference equations are applied.
#'
#' **No real patient data.** Generated by
#' `data-raw/build_pft_example.R`. Provided for examples, vignettes,
#' and quick experimentation.
#'
#' @format A tibble with 20 rows and 11 columns:
#' \describe{
#'   \item{patient_id}{Integer 1-20. Synthetic identifier.}
#'   \item{sex}{Character: `"M"` or `"F"`.}
#'   \item{age}{Numeric, years.}
#'   \item{height}{Numeric, centimetres.}
#'   \item{race}{One of `"Caucasian"`, `"AfrAm"`, `"NEAsia"`, `"SEAsia"`.}
#'   \item{fev1_measured}{Measured FEV1 in litres. May be `NA`.}
#'   \item{fvc_measured}{Measured FVC in litres.}
#'   \item{fev1fvc_measured}{Measured FEV1/FVC ratio.}
#'   \item{tlc_measured}{Measured TLC in litres. May be `NA` for rows
#'     intended to demonstrate spirometry-only workflows.}
#'   \item{fev1_pre}{Pre-bronchodilator FEV1 in litres. `NA` when not a BDR scenario.}
#'   \item{fev1_post}{Post-bronchodilator FEV1 in litres. `NA` when not a BDR scenario.}
#' }
#'
#' @source `data-raw/build_pft_example.R` (synthetic; no real patient data).
#'
#' @examples
#' data(pft_example)
#' head(pft_example)
#' pft_interpret(pft_example)
"pft_example"
